#!/usr/bin/env python3
# -*- coding: utf-8 -*-
__author__ = "jys"
__copyright__ = "Copyright (C) 2022 LATEJCON"

from os import path, environ
import datetime
import cgi
from flask import Flask, request
import re
import subprocess
# import cgitb
import traceback
from hashlib import blake2b
from ViRecherche import ViRecherche
from ViUrls import ViUrls

LIMIT=100
# MIN_FILTRE=6200000
# MAX_FILTRE=6220000
MIN_FILTRE=27500101
MAX_FILTRE=27570137

#cgitb.enable()
# cgitb.enable(display=0, logdir="logdir")

try:
    # L'en-tête qui va bien
    print("Content-Type: text/html")
    print()
    #print(path.abspath(path.curdir))

    form = cgi.FieldStorage()
    #print(form)
    # un dejtail d'implantation que je n'ai pas compris
    ressources = 'ressources/'      # cas gejnejral
    if not path.isdir(ressources): ressources = '../ressources/' # canap de Dom
    if not path.isdir(ressources): print("PAS DE RESSOURCES !!")
            
    # rejcupejration des ejvejnements et des sauvegardes
    latejcon = form.getvalue('latejcon')
    premiehreFois = not latejcon
    modedEmploi = ('modedEmploi' in form) ^ ('sansModedEmploi' not in form)
    rechercher = form.getvalue('ça')
    rechercherDesc = form.getvalue('descripteurs')
    if rechercher: texteRecherchej = form.getvalue('texteRecherchej') or ''
    else: texteRecherchej = form.getvalue('svtexteRecherchej') or ''
    svLesUrls = form.getvalue('lesUrls') or ''
    if svLesUrls == '': lesUrls = []
    else: lesUrls = svLesUrls.split(',')
    lesIdents = form.getvalue('lesIdents') or ''
    if lesIdents == '': nombreIdents = 0
    else: nombreIdents = len(lesIdents.split(','))
    nombreIdentsNf = form.getvalue('nombreIdentsNf') or ''
    if nombreIdentsNf: nombreIdentsNf = int(nombreIdentsNf)
    else: nombreIdentsNf = 0
    svLaPremiehre = form.getvalue('laPremiehre') or '0'
    laPremiehre = int(svLaPremiehre)
    laLejgende = form.getvalue('laLejgende') or ''
    laLejgende = laLejgende.replace('"', '&quot;')
    clicImage = ''
    for clef in form.keys():
        m = re.match("IMG([0-9]*).x", clef)
        if m is None: continue
        clicImage = m.group(1)
    avant = form.getvalue('avant.x')
    aprehs = form.getvalue('aprehs.x')

    # premiehre fois 
    if premiehreFois:
        #viUrls = ViUrls(ressources + 'VI')
        #lesUrls = viUrls.rechercheUrls([i for i in range(1,17)])
        texteRecherchej = "viallon"
        rechercher = True
        laLejgende = ''
        latejcon = '1'
        mparny = True
    else: mparny = latejcon != "1.732"

    # recherche
    if rechercher:
        # teste si mot de passe ok
        if mparny:
            # pas ok, teste la recherche
            h = blake2b(digest_size=10)
            h.update(texteRecherchej.lower().encode('utf8'))
            mparny = h.hexdigest() != 'ab269ffc2b6f37dbd2a2'
        if not mparny: latejcon = "1.732"
        laLejgende = ''
        
    # recherche sur descripteurs
    if rechercherDesc:
        m = re.match("([0-9]*)..*¦(.*)©.*", laLejgende)
        identImage = int(m.group(1))
        texteRecherchej = m.group(2) + ' ·'
        
    # recherches sur texte et descripteurs
    if rechercher or rechercherDesc:
        viRecherche = ViRecherche(ressources + 'VI')
        # viRecherche = ViRecherche(ressources + 'Latejcon')
        identsRecherche = viRecherche.rechercheIdentsParTexte(texteRecherchej)
        viRecherche.close()
        if rechercherDesc:
            identsRecherche.remove(identImage)
            identsRecherche.insert(0, identImage)
        # filtrage 
        nombreIdentsNf = len(identsRecherche)
        if mparny:
            identsRecherche = [ident for ident in identsRecherche if MIN_FILTRE <= ident <= MAX_FILTRE]
        # les idents et les URLs
        nombreIdents = len(identsRecherche)
        lesIdents = ','.join(["%x"%i for i in identsRecherche])
        viUrls = ViUrls(ressources + 'VI')
        lesUrls = viUrls.rechercheUrls(identsRecherche[:100])
        laPremiehre = 0

    # clic image
    if clicImage:
        # rejordonne les vignettes
        index = int(clicImage)
        lesUrls = lesUrls[index:] + lesUrls[:index]
        # trouve la lejgende
        m = re.match("([0-9]*);.*", lesUrls[0])
        identDoc = m.group(1)
        laLejgende = subprocess.getoutput(f'grep "^{identDoc}." {ressources + "VI.vicorpustxt"}').replace('"', '&quot;')
        # laLejgende = subprocess.getoutput(f'grep "^{identDoc}\." {ressources + "viCorpus.txt"}').replace('"', '&quot;')
        
    # clic avant
    if avant:
        if laPremiehre > 100: laPremiehre -= 100 
        else: laPremiehre = 0
        
    # clic aprehs
    if aprehs:
        if laPremiehre + 200 < nombreIdents: laPremiehre += 100 
        else: laPremiehre = nombreIdents -100
        
    # clic avant ou aprehs
    if avant or aprehs:
        identsRecherche = [int(i, 16) for i in lesIdents.split(',')]
        viUrls = ViUrls(ressources + 'VI')
        lesUrls = viUrls.rechercheUrls(identsRecherche[laPremiehre:laPremiehre+100])
        laLejgende = ''
        
    # la trace
    if premiehreFois or rechercher:
        fichierTrace = path.join(path.dirname(path.realpath(__file__)), '..', 'ressources/traces.csv')
        timbreDeTemps = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        if 'REMOTE_ADDR' in environ: adrIp = environ['REMOTE_ADDR']
        else: adrIp = ''
        if 'REMOTE_PORT' in environ: port = environ['REMOTE_PORT']
        else: port = ''
        if 'HTTP_USER_AGENT' in environ: agent = environ['HTTP_USER_AGENT']
        else: environ = ''
        nombreMots = len(texteRecherchej.split())
        with open(fichierTrace, 'a') as trace:
            trace.write(f'{timbreDeTemps} | {adrIp} | {port} | {agent} | {nombreMots} | {nombreIdents}\n')


    # l'en-teste
    print("""
        <html xmlns="http://www.w3.org/1999/xhtml">
        <head>
        <title>vieilles images</title>
        <link rel="icon" type="image/png" href="../ressources/faviconLaR2.png"/>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
        <style type="text/css">
        .ta1 { width:100%; height:400px; overflow:auto; font-size: 16pt; color:darkgreen; font-family: Tahoma, sans-serif; background-color: White; } 
        .ta2 { width:100%; height:400px; overflow:auto; font-size: 16pt; color:darkred; font-family: Tahoma, sans-serif; background-color: lightgrey; } 
        .ta3 { width:100%; height:400px; overflow:auto; font-size: 16pt; color:darkblue; font-family: Tahoma, sans-serif; background-color: lightgrey; } 
        a:link { text-decoration:none; } 
        sti { color:black;  font-size: 35pt; margin: 0%%; font-weight:normal; font-style: italic;}
        mi1, .mi1 { color:black; font-size: 16pt; margin: 0%%; font-weight:normal; }
        mi2, .mi2 { color:darkred; font-size: 16pt; margin: 0%%; font-weight:normal; }
        mi3, .mi3 { color:darkgreen; font-size: 16pt; margin: 0%%; font-weight:normal; }
        mi4, .mi4 { color:black; font-size: 16pt; margin: 0%%; font-weight:bold; }
        mi5, .mi5 { color:darkred }
        mi6, .mi6 { color:darkgreen }
        mi7, .mi7 { color:darkblue }
        mi8, .mi8 { color:darkblue; font-size: 16pt; margin: 0%%; font-weight:normal; }
        #af1 {margin-top: 20px; margin-bottom: 20px; margin-right: 100px; margin-left: 50px; background-color: White; }
        #af2 {margin-top: 20px; margin-bottom: 20px; margin-right: 100px; margin-left: 100px; background-color: White; }
        #af3 {margin-top: 20px; margin-bottom: 20px; margin-right: 100px; margin-left: 50px; background-color: White; }
        button {padding: 0; border: none; background: none;}
        .td1 { padding: 15px; font-size: 120%; }
        .fgris { background-color: Lavender;}
        </style>
        </head>
        """)
    # le titre
    print("""
        <body>
        <img alt="../ressources/vieillesImages-100D.png" src="../ressources/vieillesImages-100D.png"  style="float:right;"/>    
        <form action="VieillesImages" method="post">
        <table><tr><td><img src="../ressources/echiquierLatejcon4-200T.png"/></td><td><sti>et les vieilles images</sti></td></tr></table>
        """)
    # la recherche
    print(f"""
        <div id="af1">
        <p class="mi3">
        <mil>Que cherchez-vous ? </mi1>&nbsp;&nbsp;
        <input type="text" name="texteRecherchej" value="{texteRecherchej}" style="font-size: 16pt"/>
        <input type="submit" name="ça" value="&#x1F50D;" style="font-size: 16pt"/>&nbsp;&nbsp;&nbsp;&nbsp;
        """)
    if texteRecherchej:
        if nombreIdents != nombreIdentsNf: 
            textef = f'<mil> (dont {nombreIdents} publiques).</mi1>'
        else: textef = '.'
        if nombreIdentsNf == 0: 
            print('<mil>Rien trouvé, dejsolé.</mi1>')
        elif nombreIdentsNf == 1:
            print('<mil>Une seule image trouveje</mi1>' + textef)
        else: 
            print(f'<mil>{nombreIdentsNf} images trouvejes</mi1>' + textef)
            
    print("""
        </p> 
        </div>   
        """)

    # le mode d'emploi
    print("""
        <div id="af3">
        <input type="submit" name="modedEmploi" value="mode d'emploi" style="font-size: 10pt"/>
        """)
    if modedEmploi:
        if mparny:
            print("""
                <i>Pour masquer ce mode d'emploi, cliquez sur le bouton <b>mode d'emploi</b>.</i>
                <br/><u>Les vieilles images ne sont pas toutes publiques, loin de là</u>. Pour les voir toutes, il faut une clef et une
                serrure (un mot de passe et l'endroit où le mettre)... C'est pas gagné. Vous pouvez quand
                mesme demander à ivo@latejcon.art... Mais Ivo a mauvais caractehre, il faut estre diplomate...
                <br/>Mais, comme consolation, comme compensation, comme apaisement, vous pouvez chercher dans les images libres de l'Atejcon...
                """)
        else:
            print("""
                <i>Pour masquer ce mode d'emploi, cliquez sur le bouton <b>mode d'emploi</b>.</i>
                <br/>Vous avez accehs aux vieilles images, aux plus de 390&nbsp;000 vieilles images. 
                <br/>Attention, l'indexation et l'analyse du texte de recherche sont sommaires.
                Il n'y a pas d'analyse syntaxique ni mesme morphologique. 
                Aussi, si rien n'est trouvé, ça ne signifie pas obligatoirement qu'il n'y a rien à trouver, juste qu'il faut chercher diffejremment.  
                <br/><b>Faites simple</b>. Cherchez des noms propres, des mots clefs ou des dates (anneje ou mois + anneje), ne faistes pas de phrases, essayez et rejessayez et, surtout, faites simple et ne faistes pas de phrases.
                Si vous cherchez plusieurs mots (ex "Karl Marx rigolo"), les mots inconnus du systehme sont ignorejs ("rigolo") et seules les images qui ont tous les autres mots apparaistront (les images qui ont à la fois "Karl" et "Marx). 
                <br/>Cliquez sur une vignette pour voir l'image et sa lejgende et ejventuellement sur les flehches pour accéder aux images suivantes ou prejcejdents.
                """)
            
    print('</div>')

    # l'image et la lejgende
    if laLejgende:
        m = re.match("[0-9]*;(.*)", lesUrls[0])
        image = m.group(1)
        m = re.match("(.*)¦(.*)(©.*)", laLejgende)
        dejbut = m.group(1)
        descripteurs = m.group(2)
        copyright = m.group(3)
        print(f"""
            <table><tr><td>
            <img src="../400x400/{image}" alt="../400x400/{image}"/>
            </td><td class="td1">{dejbut}
            <br/><font class="fgris">{descripteurs}</font> 
            <input type="submit" name="descripteurs" value="&#x1F50D;" style="font-size: 16pt;"/>
            <br/>{copyright}
            </td></tr></table>
            """)
    
    # les vignettes
    if laPremiehre != 0:
        print(f"""
            <input type="image" name="avant" 
            src="../vignettes/avant.jpeg" alt="../vignettes/avant.jpeg"/>
            """)
    compt = 0
    for url in lesUrls:
        # 109400141;1608/10940-141.jpg
        m = re.match("[0-9]*;(.*)", url)
        vignette = m.group(1)
        print(f"""
            <input type="image" name="IMG{compt}" 
            src="../vignettes/{vignette}" alt="../vignettes/{vignette}"/>
            """) 
        compt +=1
    if laPremiehre + LIMIT < nombreIdents:
        print(f"""
            <input type="image" name="aprehs" 
            src="../vignettes/aprehs.jpeg" alt="../vignettes/aprehs.jpeg"/>
            """)
            
    # passage de l'ejtat
    if not modedEmploi: print('<input type="hidden" name="sansModedEmploi" value="1"/>')
    #if modedEmploi: print('<input type="hidden" name="avecModedEmploi" value="1"/>')
    if texteRecherchej: print(f'<input type="hidden" name="svtexteRecherchej" value="{texteRecherchej}"/>')
    print(f'<input type="hidden" name="laLejgende" value="{laLejgende}"/>')
    svLesUrls = ','.join(lesUrls)
    print(f'<input type="hidden" name="lesUrls" value="{svLesUrls}"/>')
    print(f'<input type="hidden" name="latejcon" value="{latejcon}"/>')
    print(f'<input type="hidden" name="lesIdents" value="{lesIdents}"/>')
    print(f'<input type="hidden" name="laPremiehre" value="{laPremiehre}"/>')
    print(f'<input type="hidden" name="nombreIdentsNf" value="{nombreIdentsNf}"/>')

    print('</form></body></html>')
    
except Exception:
    print("Content-Type: text/html")
    traceback.print_exc()  # Affiche la trace complète
    
